// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR7OA-it-FCXE_SA5OKXDs7ZuTtGArIkQ',
    appId: '1:659847548250:web:ad3f736c16c8f6ae1df763',
    messagingSenderId: '659847548250',
    projectId: 'cw6app',
    authDomain: 'cw6app.firebaseapp.com',
    storageBucket: 'cw6app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJN29D6ERfw56fEDjlBM8p-FC_MMiFgtk',
    appId: '1:659847548250:android:d39cda57c5d7fb5b1df763',
    messagingSenderId: '659847548250',
    projectId: 'cw6app',
    storageBucket: 'cw6app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf-Ju3N3Vv48EhsjZ4h8MjjDg3xiYcX2g',
    appId: '1:659847548250:ios:6363b64e096f48731df763',
    messagingSenderId: '659847548250',
    projectId: 'cw6app',
    storageBucket: 'cw6app.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf-Ju3N3Vv48EhsjZ4h8MjjDg3xiYcX2g',
    appId: '1:659847548250:ios:6363b64e096f48731df763',
    messagingSenderId: '659847548250',
    projectId: 'cw6app',
    storageBucket: 'cw6app.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR7OA-it-FCXE_SA5OKXDs7ZuTtGArIkQ',
    appId: '1:659847548250:web:b074d82f4df7955c1df763',
    messagingSenderId: '659847548250',
    projectId: 'cw6app',
    authDomain: 'cw6app.firebaseapp.com',
    storageBucket: 'cw6app.firebasestorage.app',
  );

}